## 從Excel讀取元大台灣50與中型100股票代碼與名稱

In [34]:
# ref: https://pandas.pydata.org/docs/user_guide/io.html#excel-files

import pandas as pd

df50 = pd.read_excel('TWSE_Stock50_20200506.xlsx', sheet_name='Sheet1')
df100 = pd.read_excel('TWSE_Stock100_20200506.xlsx', sheet_name='Sheet1')

# use concat to combine two dataframe
df150 = pd.concat([df50, df100])
code = df150['證券代碼']

1101
1102
1216
1301
1303
1326
1402
2002
2105
2207
2301
2303
2308
2317
2327
2330
2357
2382
2395
2408
2412
2454
2474
2633
2801
2823
2880
2881
2882
2883
2884
2885
2886
2887
2888
2890
2891
2892
2912
3008
3045
3711
4904
4938
5871
5876
5880
6505
9904
9910
1210
1227
1229
1319
1434
1476
1477
1504
1536
1590
1605
1707
1717
1722
1723
1802
2027
2049
2059
2101
2104
2201
2227
2231
2313
2324
2337
2344
2345
2347
2352
2353
2354
2356
2360
2371
2376
2377
2379
2383
2385
2404
2409
2439
2448
2449
2451
2492
2498
2542
2603
2606
2610
2615
2618
2809
2812
2834
2845
2867
2889
2903
2915
3005
3023
3034
3037
3044
3231
3406
3443
3481
3532
3533
3702
3706
4958
5269
5522
6176
6213
6239
6269
6278
6285
6409
6415
6456
6592
6669
8046
8341
8454
8464
9914
9917
9921
9933
9941
9945